### ISSUE TITLE
apprtc

### ISSUE THREAD

**Issue by yatin7610** [Androidhacks7/AppRTC-Android#1]
not getting call from one device to other

**Comment by Androidhacks7** [comment]
Can you explain in detail or share the client and server logs

**Comment by yatin7610** [comment]
I install all the things like node.js and install npm in server files. After that I installed ur Android app on 2 devices after installation I got the registered user list I clicked on one user which is registered on another device but nothing is happening

**Comment by Androidhacks7** [comment]
Can you post the server logs?

**Comment by yatin7610** [comment]
this is my server log

![untitled](https://cloud.githubusercontent.com/assets/16683104/12346471/87ff5dbc-bb7a-11e5-8f25-0619e07587d2.png)

**Comment by yatin7610** [comment]
but  android app not showing anything except registered users list

**Comment by Androidhacks7** [comment]
Make sure the first mobile device registered is still on the list of users screen when call is made from the second device. You should be able to see an incoming call pop-up. Also remove the db.json when you rerun the server

**Comment by yatin7610** [comment]
K I will try and let you know
