### ISSUE TITLE
Calling popup is not shown in receiver side

### ISSUE THREAD

**Issue by vikram2330** [Androidhacks7/AppRTC-Android#3]
users are registered to server but call message is not sent to other user, though it sent to server but from there user2 didn'trecieve any notification

**Comment by Androidhacks7** [comment]
The receiver will get a notification only if the application is in the foreground and when the user is registered. For background notifications you have to implement a push notification mechanism to launch the app on incoming call

**Comment by vikram2330** [comment]
App is in foreground, the matter is with app.js file which is running on server side. It is receiving messages but not sending to other client

**Comment by muscleAndroid** [comment]
thanks
